# file: roles/sourcecodeprofont/tasks/main.yml
---

- name: install fontconfig
  apt:
    name:
      - fontconfig

- name: download and extract font
  unarchive:
    src: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
    dest: /tmp
    remote_src: True

- name: create opentype dir
  file:
    path: /usr/share/fonts/openfont
    state: directory

- name: copy font to font store
  shell: cp -R /tmp/source-code-pro-2.030R-ro-1.050R-it/OTF/* /usr/share/fonts/openfont/
  args:
    creates: /usr/share/fonts/openfont/SourceCodePro-Regular.otf

- name: refresh font cache
  shell: fc-cache -f && touch /tmp/font_cache_refreshed
  args:
    creates: /tmp/font_cache_refreshed
