---
npm_config_prefix: /usr
npm_config_unsafe_perm: true
nodejs_install_npm_user: vagrant

nodejs_npm_global_packages:
  - ionic
  - cordova
  - yarn
  - vmd
  - git-cz

brew_packages:
  - kubectl
  - helm
  - istioctl
  - packer
  - terraform
  - minikube
  - openshift-cli
  - nvim

apt_cache_valid_time: 3600
apt_setup_unattended_upgrades: false
apt_install_packages:
  - linuxbrew-wrapper
  - nuget
  - wget
  - curl
  - nmap
  - snapd
  - bison
  - libpq-dev
  - tree
  - cpu-checker
  - unzip
  - aria2
  - speedtest-cli
  - telnet
  - git
  - jq
  - whois
  - dnsutils
  - net-tools
  - build-essential
  - automake
  - ruby-sqlite3
  - qemu-kvm
  - virt-manager
  - libvirt-dev
  - libvirt-bin
  - virtinst
  - bridge-utils
  - p7zip-full
  - ovmf
  - libguestfs-tools
  - ifupdown
  - software-properties-common
  - virtualbox
  - git-extras

gems:
  - rake
  - rubocop
  - rspec
  - minitest
  - serverspec
  - winrm
  - inspec-bin
  - inspec

pip_install_packages:
  - molecule
  - docker
  - awscli
  - python-vagrant
  - netaddr
  - pyopenssl
  - pywinrm
  - urllib3
  - python-openstackclient
  - python-heatclient
  - awsebcli

group_helper:
  - user: vagrant
    groups:
      - kvm
      - docker
