---

- name: install brew
  apt:
    name:
      - git
      - gcc
      - curl
      - build-essential
    update_cache: true

- name: install linuxbrew
  environment:
    CI: true
  become_user: vagrant
  become: false
  shell: sudo su - vagrant sh -c "$(curl -fsSL https://raw.githubusercontent.com/linuxbrew/install/master/install.sh)"
  args:
    creates: /home/linuxbrew

- name: Install brew packages
  become_user: vagrant
  become: false
  homebrew:
    name: "{{ brew_packages }}"
    path: /home/linuxbrew/.linuxbrew/bin
