# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "floppy" "sd_mod" "sr_mod" "hyperv_keyboard" ];
  boot.initrd.kernelModules = ["hv_balloon" "hv_netvsc" "hv_storvsc" "hv_utils" "hv_vmbus"];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  #boot.blacklistedKernelModules = [ "hyperv_fb" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6002fa6-de2f-405a-9ffe-74fb536da0ca";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/859c1673-338e-450e-84da-d16c5412e01a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest = {
    enable = true;
  };


}
