# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.useOSProber = true;

  services.logind.extraConfig = ''
      # don’t shutdown when power button is short-pressed
      HandlePowerKey=ignore
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eb90d053-382d-44fd-a1d5-c0f909ba2851";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FCEA-EA11";
      fsType = "vfat";
    };

  swapDevices = [ ];

  hardware.pulseaudio.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #mouse
  services.xserver = {
    autoRepeatDelay = 150;
    autoRepeatInterval = 50;
    xkbOptions = "caps:escape, altwin:ctrl_win";
    enable = true;
    windowManager.xmonad = import ../../packages/xmonad;
    displayManager = {
      autoLogin = {
        enable = true;
        user = "vagrant";
      };
    };
    libinput = {
      enable = true;
      # disabling mouse acceleration
      mouse = {
        accelProfile = "flat";
      };
    };
    exportConfiguration = true;
    videoDrivers = [ "nvidia" ];
    config = ''
      Section "ServerLayout"
        Identifier     "Layout0"
        Screen      0  "Screen0" 0 0
        #InputDevice    "Keyboard0" "CoreKeyboard"
        #InputDevice    "Mouse0" "CorePointer"
        Option         "Xinerama" "0"
      EndSection

      Section "Monitor"
        # HorizSync source: edid, VertRefresh source: edid
        Identifier     "Monitor0"
        VendorName     "Unknown"
        ModelName      "Acer VG252Q"
        HorizSync       255.0 - 255.0
        VertRefresh     50.0 - 240.0
        Option         "DPMS"
      EndSection

      Section "Monitor"
        Identifier     "Monitor[0]"
      EndSection

      Section "Device"
        Identifier     "Device0"
        Driver         "nvidia"
        VendorName     "NVIDIA Corporation"
        BoardName      "NVIDIA GeForce RTX 3070"
      EndSection

      Section "Screen"
        Identifier     "Screen0"
        Device         "Device0"
        Monitor        "Monitor0"
        DefaultDepth    24
        Option         "Stereo" "0"
        Option         "nvidiaXineramaInfoOrder" "DFP-2"
        Option         "metamodes" "DP-0: 1920x1080_240 +0+0"
        Option         "SLI" "Off"
        Option         "MultiGPU" "Off"
        Option         "BaseMosaic" "off"
        SubSection     "Display"
          Depth       24
        EndSubSection
      EndSection
    '';

  };

  #graphics
  hardware.opengl.enable = true;
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;

  programs.steam.enable = true;
}
