# file: roles/xmonad/tasks/main.yml
---
- name: configure display manager theme
  become: false
  file:
    src: ~/dotfiles/.Xresources
    dest: ~/.Xresources
    state: link
    force: true

- name: install xmonad
  apt:
    name:
      - xmonad
      - dmenu

- name: create .xmonad directory (is there a better way to do this?)
  become: false
  file:
    path: ~/.xmonad
    state: directory

- name: configure xmonad theme
  become: false
  file:
    src: ~/dotfiles/.xmonad/xmonad.hs
    dest: ~/.xmonad/xmonad.hs
    state: link
    force: yes

- name: open a terminal on startup
  lineinfile:
    dest: /etc/X11/Xsession
    line: 'st -e tmux new-session -A -s carver'
    insertafter: '#!/bin/sh'
