---
- name: Install dependencies
  apt:
    name:
      - build-essential

- name: Add custom ruby repo
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: install ruby
  apt:
    name:
      - ruby
      - ruby-dev

- name: install gems
  become: true
  gem:
    name: "{{ item }}"
    user_install: false
  with_items: "{{ gems }}"

- include: rails.yml
