# file: roles/home_drive/tasks/main.yml
---
# For example,

- name: format disk
  filesystem:
    fstype: ext4
    dev: /dev/sdc
    resizefs: true

- name: mount home drive at temporary location
  mount:
    path: /tmp/home
    src: /dev/sdc
    state: mounted
    fstype: ext4

- name: copy files from old home to new home
  synchronize:
    src: /home
    dest: /tmp

- name: unmount home temporary location 
  mount:
    path: /tmp/home
    src: /dev/sdc
    state: unmounted
    fstype: ext4

- name: mount at /home
  mount:
    path: /home
    src: /dev/sdc
    state: mounted
    fstype: ext4
