---

- name: ensure curl is installed
  apt:
    name: curl

- name: download oc client
  unarchive:
    src: https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
    dest: /tmp
    remote_src: true

- name: copy oc client binary to
  copy:
    src: /tmp/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit/oc
    dest: /usr/local/bin/oc
    mode: +x
    remote_src: true

- name: extract istioctl
  shell: |
    set -o pipefail
    curl -L https://git.io/getLatestIstio | sh
  args:
    chdir: /tmp
    creates: /tmp/istio-1.2.4
    executable: /bin/bash
  environment:
    - ISTIO_VERSION: 1.2.4

- name: copy istio binary
  copy:
    src: /tmp/istio-1.2.4/bin/istioctl
    dest: /usr/local/bin/istioctl
    mode: +x
    remote_src: true

- name: create minishift working dir
  file:
    path: /tmp/minishift
    state: directory

- name: download minishift
  unarchive:
    src: https://github.com/minishift/minishift/releases/download/v1.34.1/minishift-1.34.1-linux-amd64.tgz
    dest: /tmp
    remote_src: true

- name: copy minishift binary to bin
  copy:
    src: /tmp/minishift-1.34.1-linux-amd64/minishift
    dest: /usr/local/bin/minishift
    mode: +x
    remote_src: true

- name: download glooctl
  shell: |
    set -o pipefail
    curl -sL https://run.solo.io/gloo/install | sh
  args:
    creates: ~/.gloo
    executable: /bin/bash

- name: copy glooctl to bin
  copy:
    src: ~/.gloo/bin/glooctl
    dest: /usr/local/bin/glooctl
    mode: +x
    remote_src: true

# maybe we can remove this with ubuntu 20.04
# https://askubuntu.com/questions/947189/cannot-run-virtualbox-on-ubuntu-16-04
- name: fix wierd virtualbox bug
  file:
    path: /usr
    owner: root
    group: root


