---
- name: Add emacs PPA
  apt_repository:
    repo: ppa:kelleyk/emacs

- name: Install emacs and dependencies
  apt:
    name:
      - emacs26
      - xclip
      - silversearcher-ag

- name: Install ternjs
  npm:
    global: true
    name: "{{ item }}"
  with_items:
    - tern
    - js-yaml

- name: clone spacemacs
  become_user: vagrant
  become: true
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
    clone: true
    update: false
    version: develop
  tags:
    - skip_ansible_lint

- name: copy spacemacs config
  become_user: vagrant
  become: true
  copy:
    src: .spacemacs
    dest: ~/.spacemacs

# - name: update spacemacs packages
  # become_user: vagrant
  # become: true
  # shell: emacs --batch --load=~/.emacs.d/init.el && touch /tmp/spacemacs_updated
  # args:
    # executable: /bin/bash
    # creates: /tmp/spacemacs_updated
