# file: roles/spacemacs/tasks/main.yml
---

- name: install emacs and dependencies
  apt:
    name:
      - emacs
      - ispell
      - xclip
      - silversearcher-ag

# - name: install electron in a special way or vmd breaks
#   become: true
#   shell: npm -g install electron --unsafe-perm=true --allow-root && touch /tmp/electron_installed
#   args:
#     creates: /tmp/electron_installed

- name: install ternjs #npm module currently in preview
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - tern
    - js-yaml
    - vmd

- name: clone spacemacs
  become: false
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d
    clone: yes
    update: no
  tags:
    - skip_ansible_lint

- name: symlink spacemacs config
  become: false
  file:
    src: ~/dotfiles/.spacemacs
    dest: ~/.spacemacs
    state: link
    force: yes

- name: update spacemacs packages
  become: false
  shell: emacs --batch --load=~/.emacs.d/init.el && touch /tmp/spacemacs_updated
  args:
    creates: /tmp/spacemacs_updated
