---

- name: Ensure dmidecode is installed
  apt:
    name: dmidecode

- name: Detect Hypervisor
  command: dmidecode -s system-product-name
  changed_when: false
  ignore_errors: true
  register: hypervisor

- name: Start parallels dynamic resolution tool at startup
  lineinfile:
    dest: /etc/X11/Xsession
    line: prlcc&
    insertafter: '#!/bin/sh'
  when: hypervisor.stdout == 'Parallels Virtual Platform'

- name: Install Vmware desktop tools
  apt:
    name: open-vm-tools-desktop
  when: hypervisor.stdout == 'VMware Virtual Platform'

- name: Start vmware dynamic resolution tool at startup
  lineinfile:
    dest: /etc/X11/Xsession
    line: /usr/bin/vmware-user-suid-wrapper
    insertafter: '#!/bin/sh'
  when: hypervisor.stdout == 'VMware Virtual Platform'
