# file: roles/xmonad/tasks/main.yml
---


- name: add cabal repository
  apt_repository:
    repo: ppa:hvr/ghc

- name: install xmonad prerequisites
  apt:
    name:
      - libxss-dev
      - libxrandr-dev
      - suckless-tools
      - cabal-install

- name: update cabal
  command: cabal update
  changed_when: false

- name: Install xmonad
  command: cabal install xmonad
  args:
    creates: /root/.cabal/bin/xmonad

- name: add xmonad to path
  copy:
    src: /root/.cabal/bin/xmonad
    dest: /usr/bin/xmonad
    remote_src: true
    mode: +x

- name: Install xmonad extension library
  command: cabal install xmonad-contrib
  args:
    creates: /home/vagrant/.cabal/packages/hackage.haskell.org/xmonad-contrib

- name: create .xmonad directory (is there a better way to do this?)
  become_user: vagrant
  become: true
  file:
    path: ~/.xmonad
    state: directory

- name: configure xmonad theme
  become_user: vagrant
  become: true
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/xmonad.hs
