---
- name: add cabal repository
  apt_repository:
    repo: ppa:hvr/ghc

- name: install xmonad prerequisites
  apt:
    name:
      - libxss-dev
      - libxrandr-dev
      - suckless-tools
      - cabal-install
      - xmonad
      - compton
      - feh

- name: update cabal
  become: false
  command: cabal update
  changed_when: false

- name: Install xmonad extension library
  become: false
  command: cabal install xmonad-contrib
  args:
    creates: /home/vagrant/.cabal/packages/hackage.haskell.org/xmonad-contrib

- name: create .xmonad directory (is there a better way to do this?)
  become_user: vagrant
  become: true
  file:
    path: ~/.xmonad
    state: directory

- name: configure xmonad theme
  become_user: vagrant
  become: true
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/xmonad.hs

- name: start compton with x
  lineinfile:
    dest: /etc/X11/Xsession
    line: compton &
    insertafter: '#!/bin/sh'

- name: copy wallpaper
  copy:
    src: wallpaper.png
    dest: /etc/wallpaper.png
