# file: roles/dotfiles/tasks/main.yml
---

- name: copy configs from host box
  become: false
  copy:
    src: '{{item}}'
    dest: '{{item}}'
    mode: 0400
  with_items:
    - ~/.ssh/id_rsa
    - ~/.ssh/config
    - ~/.gitconfig

- name: clone dotfiles
  become: false
  git:
    repo: git@bitbucket.org:jamesla/dotfiles.git
    accept_hostkey: yes
    dest: ~/dotfiles
    clone: yes
    update: yes
  tags:
    - skip_ansible_lint
