# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-minimal sudo bash ca-certificates && apt-get clean
RUN useradd -m vagrant && echo "vagrant:vagrant" | chpasswd && adduser vagrant sudo
RUN echo "vagrant ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
