---
dependency:
  name: galaxy
  options:
    role-file: ansible/requirements.yml
driver:
  driver:
  name: docker
platforms:
  - name: debian
    image: jrei/systemd-debian:10
    command: /sbin/init
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
    security_opts:
      - seccomp=unconfined
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: true
  playbooks:
    converge: ../../ansible/playbook.yml
  env:
    ANSIBLE_ROLES_PATH: /tmp/molecule/ansible/default:../roles
scenario:
  name: default
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - dependency
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - dependency
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
# lint: |
  # set -e
  # yamllint .
  # ansible-lint
verifier:
  name: ansible
