---

- name: Ensure timezone dependencies are installed
  apt:
    name:
      - ntp
      - locales
      - language-pack-en

- name: Set timezone
  timezone:
    name: Australia/Sydney

- name: Set locale
  locale_gen:
    name: en_US.UTF-8

- name: Set locale
  shell: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && touch /tmp/local_updated
  args:
    executable: /bin/bash
    creates: /tmp/local_updated
