---

- name: Ensure timezone dependencies are installed
  apt:
    name:
      - ntp
      - locales

- name: Set timezone
  timezone:
    name: Australia/Sydney

- name: Set locale
  locale_gen:
    name: en_US.UTF-8
