# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  boot.initrd.availableKernelModules =
    [ "uhci_hcd" "xhci_pci" "ehci_pci" "ata_piix" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.loader.grub.devices = [ "/dev/sda" ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/vagrant" = {
    device = "/media/psf/vagrant";
    options = [ "uid=1000" "gid=1000" "nofail" ];
    fsType = "prl_fs";
  };

  swapDevices = lib.mkForce [ ];

  services.xserver = {
    autoRepeatDelay = 150;
    autoRepeatInterval = 50;
    xkb = {
      options = "caps:escape, altwin:ctrl_win";
    };
    enable = true;
    windowManager.xmonad = import ../../packages/xmonad;
    exportConfiguration = true;
  };

  services.displayManager = {
    autoLogin = {
      enable = true;
      user = "vagrant";
    };
  };

  services.libinput = {
    enable = true;
    # disabling mouse acceleration
    mouse = {
      accelProfile = "flat";
    };
  };

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.parallels = {
    enable = true;
  };
}

