# file: roles/stterm/tasks/main.yml
---

- name: download and extract stterm
  unarchive:
    src: http://dl.suckless.org/st/st-0.7.tar.gz
    dest: /tmp
    remote_src: True

- name: get solarize theme patch prereq
  get_url:
    url: http://st.suckless.org/patches/st-no_bold_colors-20160727-308bfbf.diff
    dest: /tmp/st-0.7/st-no_bold_colors-20160727-308bfbf.diff

- name: get select clipboard patch
  get_url:
    url: http://st.suckless.org/patches/st-clipboard-20160727-308bfbf.diff
    dest: /tmp/st-0.7/st-clipboard-20160727-308bfbf.diff

- name: get solarize theme patches
  get_url:
    url: http://st.suckless.org/patches/st-solarized-dark-20160727-308bfbf.diff
    dest: /tmp/st-0.7/st-solarized-dark-20160727-308bfbf.diff

- name: apply patches
  shell: cd /tmp/st-0.7 && git apply st-no_bold_colors-20160727-308bfbf.diff && git apply st-solarized-dark-20160727-308bfbf.diff && git apply st-clipboard-20160727-308bfbf.diff && touch /tmp/patches_applied
  args:
    creates: /tmp/patches_applied

- name: compile
  shell: cd /tmp/st-0.7 && make clean install
  args:
    creates: /usr/local/bin/st
