---
driver:
  name: vagrant
  ssh:
    shell: /bin/sh

# driver:
#   name: docker
#   use_sudo: false
#   provision_command: mkdir -p /run/sshd
#   disable_upstart: false
#   ssh:
#     shell: '"/bin/sh"'

provisioner:
  name: ansible_playbook
  additional_copy_path: pre_tasks
  requirements_path: requirements.yml
  playbook: playbook.yml
  hosts: default
  # ansible_verbose: true
  roles_path: roles
  require_chef_for_busser: false
  ansible_sudo: false

platforms:
  - name: ubuntu-17.10
    driver:
      username: vagrant
      password: vagrant

# verifier:
#   name: serverspec
#   sudo: true
#   sudo_command: 'sudo -E -H -u vagrant'
#   custom_install_commmand: echo 123
  # remote_exec: false
  # sudo_path: true

# suites:
#   - name: default
#     run_list:
#     attributes:

suites:
  - name: default
    verifier:
      patterns:
        - spec/carveros/*_spec.rb
