---
molecule:
  test:
    sequence:
    - destroy
    - syntax
    - create
    - converge
    - verify
dependency:
  name: galaxy
  requirements_file: requirements.yml
  verbose: true
driver:
  name: vagrant
vagrant:
  platforms:
    - name: ubuntu
      box: jamesla/ubuntu-1604-min-daily
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2500
        cpus: 4
  append_platform_to_hostname: false
  instances:
    - name: carveros
verifier:
  name: serverspec
