---

- hosts: all
  become: true
  pre_tasks:
    - include: pre_tasks/set-timezone.yml
  roles:
    - {role: brew}
    - {role: ansible-role-nodejs}
    - {role: ansible-role-apt}
    - {role: ansible-role-pip}
    - {role: ansible-go}
    - {role: ansible-role-dotnet-core}

    - {role: ruby}
    - {role: spacevim}
    - {role: spacemacs}
    - {role: desktop}
    - {role: ansible-role-tmux}
    - {role: terminal}

    - {role: ansible-role-gcloud}
    - {role: ansible-vagrant}
    - {role: ansible-role-chrome}
    - {role: docker}
    - {role: ansible-role-grouphelper}
    - {role: ansible-role-visual-studio-code}
