---

- hosts: all
  become: true
  pre_tasks:
    - include: pre_tasks/set-timezone.yml
  roles:
    - {role: ansible-role-pip}
    - {role: ansible-role-apt}
    - {role: ansible-role-nodejs}
    - {role: ansible-go}

    - {role: ruby}
    - {role: spacemacs}
    - {role: desktop}
    - {role: ansible-role-tmux}
    - {role: terminal}

    - {role: ansible-kubectl}
    - {role: ansible-minikube}
    - {role: ansible-packer}
    - {role: ansible-vagrant}
    - {role: ansible-role-terraform}
    - {role: ansible-consul}
    - {role: ansible-role-chrome}
    - {role: docker}
    - {role: ansible-virtualbox}
    - {role: ansible-role-grouphelper}
    - {role: ansible-role-visual-studio-code}
