---
# install python2.7 (ansible dependendy)
# this can be removed once python3 support is official
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - include: pre_tasks/install-python-2.7.yml

- hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - include: pre_tasks/set-timezone.yml
  roles:
    - { role: home_drive }
    - { role: ansible-role-apt }
    - { role: ansible-curl }
    - { role: ansible-role-git }
    - { role: ansible-role-nodejs }
    - { role: ansible-role-pip }
    - { role: ansible-go }

    - { role: fish }
    - { role: ansible-rbenv-role }
    - { role: dotfiles }
    - { role: spacemacs }
    - { role: vim }
    - { role: tmux }
    - { role: xmonad }
    - { role: parallel_tools_fixes }

    - { role: ansible-virtualbox }
    - { role: docker-ubuntu }
    - { role: ansible-packer }
    - { role: ansible-vagrant }
    - { role: ansible-role-chrome }
    - { role: ansible-consul }
    - { role: ansible-consul-template }
    - { role: ansible-terraform }
