- src: https://github.com/geerlingguy/ansible-role-git.git
  version: master
  name: ansible-role-git

- src: https://github.com/angstwad/docker.ubuntu.git
  version: master
  name: docker-ubuntu

- src: https://github.com/rvm/rvm1-ansible.git
  version: master
  name: rvm_io.ruby

- src: https://github.com/andrewrothstein/ansible-curl.git
  version: master
  name: ansible-curl

- src: https://github.com/geerlingguy/ansible-role-nodejs.git
  version: master
  name: ansible-role-nodejs

- src: https://github.com/cmprescott/ansible-role-chrome.git
  version: master
  name: ansible-role-chrome

- src: https://github.com/bobbyrenwick/ansible-pip.git
  version: master
  name: ansible-pip

- src: https://github.com/geerlingguy/ansible-role-packer-debian.git
  version: master
  name: ansible-role-packer-debian

- src: https://github.com/andrewrothstein/ansible-vagrant.git
  version: master
  name: ansible-vagrant

- src: https://github.com/andrewrothstein/ansible-packer.git
  version: master
  name: ansible-packer
