---
- name: add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: install fish shell
  apt:
    name: fish

- name: Create fish directory
  become: true
  become_user: vagrant
  file:
    path: ~/.config/fish
    state: directory

- name: Create function directory
  become: true
  become_user: vagrant
  file:
    path: ~/.config/fish/functions
    state: directory

- name: copy fish config
  become: true
  become_user: vagrant
  template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish

- name: copy fish functions
  become: true
  become_user: vagrant
  template:
    src: fish_prompt.fish.j2
    dest: ~/.config/fish/functions/fish_prompt.fish

- name: set pam to allow shell change (possible bug in ubuntu 16)
  lineinfile:
    path: /etc/pam.d/chsh
    regexp: 'auth       required   pam_shells.so'
    line: '#auth       required   pam_shells.so'

- name: Set as default shell
  become: true
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items:
    - root
    - vagrant

- name: Install fisher
  become: true
  become_user: vagrant
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Install fisher
  become: true
  become_user: vagrant
  shell: fisher add evanlucas/fish-kubectl-completions && touch /tmp/fisher_kubectl_completions
  args:
    creates: /tmp/fisher_kubectl_completions
