---
- name: add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3

- name: install fish shell
  apt:
    name:
      - fish
      - git

- name: Create fish directory
  become: true
  become_user: vagrant
  file:
    path: ~/.config/fish
    state: directory

- name: Create function directory
  become: true
  become_user: vagrant
  file:
    path: ~/.config/fish/functions
    state: directory

- name: copy fish config
  become: true
  become_user: vagrant
  template:
    src: config.fish.j2
    dest: ~/.config/fish/config.fish

- name: copy fish functions
  become: true
  become_user: vagrant
  template:
    src: fish_prompt.fish.j2
    dest: ~/.config/fish/functions/fish_prompt.fish

- name: set pam to allow shell change (possible bug in ubuntu 16)
  lineinfile:
    path: /etc/pam.d/chsh
    regexp: 'auth       required   pam_shells.so'
    line: '#auth       required   pam_shells.so'

- name: Set as default shell
  become: true
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items:
    - root
    - vagrant

- name: Install fisher
  become: true
  become_user: vagrant
  get_url:
    url: https://git.io/fisher
    dest: ~/.config/fish/functions/fisher.fish

- name: Install fisher plugins
  become: true
  become_user: vagrant
  shell: fisher add evanlucas/fish-kubectl-completions && touch /tmp/fisher_kubectl_completions
  args:
    creates: /tmp/fisher_kubectl_completions
    executable: /usr/bin/fish

- name: Install krew
  shell: |
    set -o pipefail
    begin
      set -x; set temp_dir (mktemp -d); cd "$temp_dir" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.{tar.gz,yaml}" &&
      tar zxvf krew.tar.gz &&
      set KREWNAME krew-(uname | tr '[:upper:]' '[:lower:]')_amd64 &&
      ./$KREWNAME install \
        --manifest=krew.yaml --archive=krew.tar.gz &&
      set -e KREWNAME; set -e temp_dir
    end
  args:
    creates: /tmp/krew_installed
    executable: /usr/bin/fish
