# file: roles/stterm/tasks/main.yml
---
- name: install stterm dependencies
  apt:
    name:
      - build-essential
      - libxft-dev

- name: download and extract stterm
  unarchive:
    src: http://dl.suckless.org/st/st-0.7.tar.gz
    dest: /tmp
    remote_src: True
  args:
    creates: /tmp/st-0.7

- name: get solarize theme patch prereq
  copy:
    src: "{{ item }}"
    dest: /tmp/st-0.7
  with_items:
    - "{{ role_path }}/files/st-clipboard-20160727-308bfbf.diff"
    - "{{ role_path }}/files/st-no_bold_colors-20160727-308bfbf.diff"
    - "{{ role_path }}/files/st-solarized-dark-20160727-308bfbf.diff"

- name: apply patches
  shell: cd /tmp/st-0.7 && git apply st-no_bold_colors-20160727-308bfbf.diff && git apply st-solarized-dark-20160727-308bfbf.diff && git apply st-clipboard-20160727-308bfbf.diff && touch /tmp/st-0.7/patches_applied
  args:
    executable: /bin/bash
    creates: /tmp/st-0.7/patches_applied

- name: compile
  shell: cd /tmp/st-0.7 && make clean install
  args:
    executable: /bin/bash
    creates: /usr/local/bin/st
