---
- name: install stterm dependencies
  apt:
    name:
      - build-essential
      - libxft-dev
      - git

- name: download and extract stterm
  unarchive:
    src: http://dl.suckless.org/st/st-0.8.2.tar.gz
    dest: /tmp
    remote_src: true
  args:
    creates: /tmp/st-0.8.2

- name: get solarize theme patch prereq
  copy:
    src: "{{ item }}"
    dest: /tmp/st-0.8.2
  with_items:
    - st-clipboard-0.8.2.diff
    - st-alpha-0.8.2.diff
    - st-no_bold_colors-0.8.1.diff
    - st-solarised-dark-after-alpha-0.8.2.diff

- name: apply patches
  shell: |
    #!/usr/bin/env bash
    set -e
    git apply st-clipboard-0.8.2.diff
    git apply st-alpha-0.8.2.diff
    git apply st-no_bold_colors-0.8.1.diff
    git apply st-solarised-dark-after-alpha-0.8.2.diff
    touch patches_applied
  args:
    executable: /bin/bash
    creates: /tmp/st-0.8.2/patches_applied
    chdir: /tmp/st-0.8.2

- name: compile
  shell: cd /tmp/st-0.8.2 && make clean install
  args:
    executable: /bin/bash
    creates: /usr/local/bin/st
