# file: roles/tmux/tasks/main.yml
---

- name: copy tmux config
  become_user: vagrant
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: ~/.tmux.conf

- name: install tmux plugins
  become_user: vagrant
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    clone: yes
    update: no
    version: v3.0.0

- name: update tmux plugins
  become_user: vagrant
  shell: ~/.tmux/plugins/tpm/bin/install_plugins && touch ~/.tmux/tpm_output
  args:
    executable: /bin/bash
    creates: ~/.tmux/tpm_output
